name: Cobalto Pipeline

on:
  push:
    tags:
      - '*'

jobs:

  build_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env release
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set env slug
        run: echo "REPO_SLUG=cobalto" >> $GITHUB_ENV
#      - uses: docker/setup-qemu-action@v2
      - name: Login into registry
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo ${DOCKERHUB_TOKEN} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
      - name: Build and Publish Image
        env:
          DOCKERHUB_NAMESPACE: ${{ secrets.DOCKERHUB_NAMESPACE }}
        run: bash build_all.sh ${DOCKERHUB_NAMESPACE}/${REPO_SLUG} ${RELEASE_VERSION}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env release
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set env slug
        run: echo "REPO_SLUG=cobalto" >> $GITHUB_ENV
      - uses: burnett01/rsync-deployments@5.2
        name: Pre Deploy
        env:
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ vars.SSH_PORT }}
          COMMON_BASE_PATH: ${{ vars.COMMON_BASE_PATH }}
          DOCKERHUB_NAMESPACE: ${{ secrets.DOCKERHUB_NAMESPACE }}
        with:
          switches: -ravP --exclude=".git*" --exclude="readme.md" --exclude="src"
          path: deployment/
          remote_path: /root/cobalto/
          remote_host: ${{ vars.SSH_HOST }}
          remote_port: ${{ vars.SSH_PORT }}
          remote_user: ${{ secrets.SSH_REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: appleboy/ssh-action@v1.0.0
        name: Deploy IaC
        env:
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ vars.SSH_PORT }}
          COMMON_BASE_PATH: ${{ vars.COMMON_BASE_PATH }}
          DOCKERHUB_NAMESPACE: ${{ secrets.DOCKERHUB_NAMESPACE }}
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ vars.SSH_PORT }}
          envs: RELEASE_VERSION,REPO_SLUG,COMMON_BASE_PATH,DOCKERHUB_NAMESPACE
          script_stop: true
          script: |
            cd ${COMMON_BASE_PATH}/${REPO_SLUG}
            cp docker-compose.production.yml docker-compose.yml
            cp .env.production .env
            docker compose down
            docker compose up -d
