name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build frontend assets
      run: |
        cd app
        yarn install
        yarn build
        

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cobalto:$(date +%s)
        docker image ls

